export const REQUEST_ALL_POSTS = `REQUEST_ALL_POSTS`
export const SAVE_FEATURED_POSTS = `GET_FEATURED_POSTS`
export const SAVE_ALL_POSTS = `SAVE_ALL_POSTS`
export const GET_ALL_POSTS = `GET_ALL_POSTS`

export const REQUEST_ALL_TOPICS = `REQUEST_ALL_TOPICS`
export const SAVE_FEATURED_TOPICS = `GET_FEATURED_TOPICS`
export const SAVE_ALL_TOPICS = `SAVE_ALL_TOPICS`
export const GET_ALL_TOPICS = `GET_ALL_TOPICS`

export const REQUEST_ONE_POST = `REQUEST_ONE_POST`
export const SAVE_ONE_POST = `SAVE_ONE_POST`
export const GET_ONE_POST = `GET_ONE_POST`

export const GET_ONE_TOPIC = `GET_ONE_TOPIC`

export const GET_ONE_PROFILE = `GET_ONE_PROFILE`

export const ACCOUNT_REGISTER = `ACCOUNT_REGISTER`
export const ACCOUNT_LOGIN = `ACCOUNT_LOGIN`
export const ACCOUNT_LOGOUT = `ACCOUNT_LOGOUT`

export const SET_LOGIN_TOKEN = `SET_LOGIN_TOKEN`
export const SET_DECODED_ACCOUNT = `SET_DECODED_ACCOUNT`

export const SUBMIT_NEW_POST = `SUBMIT_NEW_POST`

export const LOADING_TRUE = `LOADING_TRUE`
export const LOADING_FALSE = `LOADING_FALSE`

export const HANDLE_ERROR = `HANDLE_ERROR`
