export const GET_FEATURED_POSTS = `GET_FEATURED_POSTS`
export const GET_POSTS = `GET_POSTS`
export const GET_TOPICS = `GET_TOPICS`

export const SELECT_POST = `SELECT_POST`
export const SELECT_TOPIC = `SELECT_TOPIC`
export const SELECT_PROFILE = `SELECT_PROFILE`

export const ACCOUNT_REGISTER = `ACCOUNT_REGISTER`
export const ACCOUNT_LOGIN = `ACCOUNT_LOGIN`
export const ACCOUNT_LOGOUT = `ACCOUNT_LOGOUT`

export const SET_LOGIN_TOKEN = `SET_LOGIN_TOKEN`
export const SET_DECODED_ACCOUNT = `SET_DECODED_ACCOUNT`

export const SUBMIT_NEW_POST = `SUBMIT_NEW_POST`

export const LOADING_TRUE = `LOADING_TRUE`
export const LOADING_FALSE = `LOADING_FALSE`
